"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { clearStudentSession, getStudentSession, type StudentSession } from "../lib/student-store";
import { CircleAlert, CircleCheck, Clock3, FileDown, Wallet } from "lucide-react";
import { StudentPortalShell } from "../components/student-portal-shell";

type FeeItem = { id: string; name: string; amount_due: number | string; amount_paid: number; balance: number; session: string; term: string };
type Payment = { id: string; fee_item_id: string; fee_name: string; amount: number | string; reference: string; status: "completed" | "pending" | "failed"; paid_at: string | null; created_at: string; notes: string | null };
type FeeData = { fee_items: FeeItem[]; payments: Payment[]; total_due: number; total_paid: number };
const nav = [{ label: "Dashboard", href: "/dashboard" }, { label: "My Subjects", href: "/courses" }, { label: "CBT / Exams", href: "/cbt" }, { label: "Results", href: "/results" }, { label: "Fees", href: "/fees" }, { label: "Timetable", href: "/timetable" }, { label: "Announcements", href: "/announcements" }, { label: "Profile", href: "/profile" }];
const money = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 2 });
const date = (value: string | null) => value ? new Date(value).toLocaleDateString("en-NG", { dateStyle: "medium" }) : "—";

function downloadReceipt(payment: Payment, student: StudentSession, feeName: string) {
  if (payment.status !== "completed") return;
  const lines = ["UNIALEGE SCHOOL", "PAYMENT RECEIPT", "", `Student: ${student.fullName}`, `Admission number: ${student.admissionNumber}`, `Class: ${student.className}`, `Fee item: ${feeName}`, `Amount: ${money.format(Number(payment.amount))}`, `Reference: ${payment.reference}`, `Paid on: ${date(payment.paid_at)}`];
  const blob = new Blob([lines.join("\r\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob); const anchor = document.createElement("a");
  anchor.href = url; anchor.download = `unialege-receipt-${payment.reference.replace(/[^a-z0-9-_]/gi, "_")}.txt`; anchor.click(); URL.revokeObjectURL(url);
}

export default function FeesPage() {
  const router = useRouter();
  const [student, setStudent] = useState<StudentSession | null>(null);
  const [data, setData] = useState<FeeData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => {
    const current = getStudentSession();
    if (!current) { router.replace("/login"); return; }
    setStudent(current);
    void fetch("/api/student/fees", { cache: "no-store", credentials: "same-origin" }).then(async (response) => {
      const body = await response.json() as FeeData & { error?: string };
      if (response.status === 401) { clearStudentSession(); router.replace("/login"); return; }
      if (!response.ok) throw new Error(body.error ?? "Unable to load your fee account.");
      setData(body);
    }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load your fee account."))
      .finally(() => setLoading(false));
  }, [router]);
  if (!student) return <main className="min-h-screen bg-slate-50" aria-busy="true" />;
  const due = data?.total_due ?? 0; const paid = data?.total_paid ?? 0; const balance = Math.max(0, due - paid);
  const paymentStatus = !data?.fee_items.length ? "No fee schedule" : balance <= 0 ? "Paid" : paid > 0 ? "Partially paid" : "Outstanding";
  const statusTone = paymentStatus === "Paid" ? "text-emerald-700 bg-emerald-50" : paymentStatus === "Outstanding" ? "text-amber-700 bg-amber-50" : paymentStatus === "No fee schedule" ? "text-slate-600 bg-slate-100" : "text-blue-700 bg-blue-50";
  return <StudentPortalShell title="School Fees" student={student} period={`${student.session} · ${student.term}`} onLogout={clearStudentSession}>
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-blue-700 dark:text-blue-300">Student account · {student.session}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950 dark:text-white sm:text-3xl">Fees & payments</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Review your current fee schedule and recorded payment activity.</p></div><span className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">{student.className} · {student.term}</span></section>
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/40 dark:text-red-200">{error}</p>}
    {loading ? <div role="status" className="rounded-xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-900">Loading fee account…</div> : <>
      <section aria-label="Fee summary" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Amount due", money.format(due), Wallet], ["Amount paid", money.format(paid), CircleCheck], ["Balance", money.format(balance), CircleAlert], ["Account status", paymentStatus, Clock3]].map(([label, value, Icon]) => <article key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5"><div className="flex items-center justify-between gap-3"><p className="text-[11px] font-medium text-slate-500 dark:text-slate-400">{String(label)}</p><span className="rounded-lg bg-blue-50 p-2 text-blue-700 dark:bg-blue-400/10 dark:text-blue-300"><Icon className="h-4 w-4" /></span></div><p className="mt-4 text-xl font-semibold tracking-tight text-slate-950 dark:text-white">{String(value)}</p>{label === "Account status" && <span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold ${statusTone}`}>{paymentStatus}</span>}</article>)}</section>
      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 dark:border-slate-800 sm:flex-row sm:items-center sm:px-6"><div><h2 className="text-sm font-semibold dark:text-white">Fee schedule</h2><p className="mt-1 text-xs text-slate-500">Items recorded for {student.session}, {student.term}.</p></div><button type="button" disabled title="Payment gateway setup is required before online payments can be accepted." className="inline-flex cursor-not-allowed items-center gap-2 self-start rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-400 dark:bg-slate-800"><Wallet className="h-4 w-4" />Make payment unavailable</button></div>
        {data?.fee_items.length ? <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-400 dark:bg-slate-800/70"><tr>{["Fee item","Amount due","Amount paid","Balance"].map((heading)=><th key={heading} className="px-5 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{data.fee_items.map((item)=><tr key={item.id}><td className="px-5 py-4 font-semibold text-slate-800 dark:text-slate-100">{item.name}</td><td className="px-5 py-4 text-slate-600 dark:text-slate-300">{money.format(Number(item.amount_due))}</td><td className="px-5 py-4 text-slate-600 dark:text-slate-300">{money.format(item.amount_paid)}</td><td className="px-5 py-4 font-semibold text-slate-900 dark:text-white">{money.format(item.balance)}</td></tr>)}</tbody></table></div><div className="grid gap-3 p-4 md:hidden">{data.fee_items.map((item)=><article key={item.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h3 className="text-sm font-semibold dark:text-white">{item.name}</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Amount due</dt><dd className="mt-1 font-medium">{money.format(Number(item.amount_due))}</dd></div><div><dt className="text-slate-400">Amount paid</dt><dd className="mt-1 font-medium">{money.format(item.amount_paid)}</dd></div><div className="col-span-2 border-t pt-2 dark:border-slate-700"><dt className="text-slate-400">Balance</dt><dd className="mt-1 font-semibold">{money.format(item.balance)}</dd></div></dl></article>)}</div></> : <div className="p-10 text-center"><Wallet className="mx-auto h-8 w-8 text-slate-300"/><h3 className="mt-3 text-sm font-semibold dark:text-white">No fee items recorded</h3><p className="mt-1 text-xs text-slate-500">There are no fee items for this class and academic period.</p></div>}
      </section>
      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b border-slate-100 p-5 dark:border-slate-800 sm:px-6"><h2 className="text-sm font-semibold dark:text-white">Payment history</h2><p className="mt-1 text-xs text-slate-500">Recorded transactions and downloadable receipts.</p></div>
        {data?.payments.length ? <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-400 dark:bg-slate-800/70"><tr>{["Date","Fee item","Reference","Amount","Status","Receipt"].map((heading)=><th key={heading} className="px-4 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{data.payments.map((payment)=><tr key={payment.id}><td className="px-4 py-4">{date(payment.paid_at ?? payment.created_at)}</td><td className="px-4 py-4 font-medium">{payment.fee_name}</td><td className="px-4 py-4 font-mono text-[10px]">{payment.reference}</td><td className="px-4 py-4">{money.format(Number(payment.amount))}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${payment.status === "completed" ? "bg-emerald-50 text-emerald-700" : payment.status === "pending" ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>{payment.status}</span></td><td className="px-4 py-4">{payment.status === "completed" ? <button type="button" onClick={() => downloadReceipt(payment, student, payment.fee_name)} className="inline-flex items-center gap-1 font-semibold text-blue-700 hover:underline"><FileDown className="h-3.5 w-3.5"/>Receipt</button> : <span className="text-slate-400">—</span>}</td></tr>)}</tbody></table></div><div className="space-y-3 p-4 md:hidden">{data.payments.map((payment)=><article key={payment.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold dark:text-white">{payment.fee_name}</h3><p className="mt-1 font-mono text-[10px] text-slate-400">{payment.reference}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${payment.status === "completed" ? "bg-emerald-50 text-emerald-700" : payment.status === "pending" ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>{payment.status}</span></div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-slate-500">{date(payment.paid_at ?? payment.created_at)}</span><strong>{money.format(Number(payment.amount))}</strong></div>{payment.status === "completed" && <button type="button" onClick={() => downloadReceipt(payment, student, payment.fee_name)} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-blue-700"><FileDown className="h-4 w-4"/>Download receipt</button>}</article>)}</div></> : <p className="p-10 text-center text-xs text-slate-500">No payment transactions are recorded for this account.</p>}
      </section>
    </>}
  </StudentPortalShell>;
}