-- JSS1 core-subject starter batch. Safe to re-run: the question-bank unique
-- index and ON CONFLICT DO NOTHING prevent duplicate level/subject prompts.
-- All questions are newly authored for UniAllege and mapped to broad JSS1 topics.

insert into public.question_bank (
  level, category, subject, topic, question,
  option_a, option_b, option_c, option_d, correct_answer,
  explanation, difficulty, marks
) values
('JSS1', null, 'Mathematics', 'Place value', 'What is the value of the digit 4 in 5,407?', '4', '40', '400', '4,000', 'C', 'The 4 is in the hundreds place, so its value is 400.', 'easy', 1),
('JSS1', null, 'Mathematics', 'Factors and multiples', 'What is the highest common factor of 18 and 24?', '3', '6', '9', '12', 'B', 'The common factors are 1, 2, 3 and 6; the greatest is 6.', 'medium', 1),
('JSS1', null, 'Mathematics', 'Fractions', 'What is three quarters plus one eighth?', '4/12', '5/8', '7/8', '1', 'C', 'Three quarters is six eighths; six eighths plus one eighth is seven eighths.', 'medium', 1),
('JSS1', null, 'Mathematics', 'Ratio', 'The ratio of red to blue beads is 2:3. If there are 25 beads altogether, how many are red?', '10', '12', '15', '20', 'A', 'There are five equal parts; each part is 5 beads, so red beads number 2 × 5 = 10.', 'medium', 1),
('JSS1', null, 'Mathematics', 'Perimeter', 'A rectangular classroom board is 8 m long and 5 m wide. What is its perimeter?', '13 m', '26 m', '40 m', '80 m', 'B', 'Perimeter = 2 × (length + width) = 2 × (8 + 5) = 26 m.', 'easy', 1),
('JSS1', null, 'Mathematics', 'Angles', 'Two angles lie on a straight line. If one is 65°, what is the other?', '25°', '65°', '115°', '125°', 'C', 'Angles on a straight line sum to 180°, so 180° − 65° = 115°.', 'medium', 1),
('JSS1', null, 'Mathematics', 'Decimals', 'What is 0.6 multiplied by 10?', '0.06', '0.6', '6', '60', 'C', 'Multiplying a decimal by 10 moves the decimal point one place to the right.', 'easy', 1),
('JSS1', null, 'Mathematics', 'Statistics', 'Find the mode of 2, 3, 3, 4 and 5.', '2', '3', '4', '5', 'B', 'The mode is the value occurring most often; 3 occurs twice.', 'easy', 1),

('JSS1', null, 'English Studies', 'Parts of speech', 'In “The tall boy carried the bag,” which word is an adjective?', 'The', 'tall', 'carried', 'bag', 'B', 'Tall describes the noun boy, so it is an adjective.', 'easy', 1),
('JSS1', null, 'English Studies', 'Verbs and tense', 'Choose the sentence that correctly tells what happened yesterday.', 'She writes a letter yesterday.', 'She wrote a letter yesterday.', 'She will write a letter yesterday.', 'She writing a letter yesterday.', 'B', 'Wrote is the past tense of write and agrees with the time marker yesterday.', 'easy', 1),
('JSS1', null, 'English Studies', 'Vocabulary', 'Which word is closest in meaning to “rapid”?', 'Slow', 'Quick', 'Weak', 'Quiet', 'B', 'Rapid means happening or moving quickly.', 'easy', 1),
('JSS1', null, 'English Studies', 'Punctuation', 'Which punctuation mark belongs at the end of “Where is my exercise book”?', 'Full stop (.)', 'Comma (,)', 'Question mark (?)', 'Apostrophe (’)', 'C', 'The sentence asks a direct question and ends with a question mark.', 'easy', 1),
('JSS1', null, 'English Studies', 'Nouns and number', 'What is the correct plural form of “child”?', 'Childs', 'Childes', 'Children', 'Childrens', 'C', 'Children is the standard irregular plural of child.', 'easy', 1),
('JSS1', null, 'English Studies', 'Sentence structure', 'What is the subject of “The birds flew over the roof”?', 'Flew', 'Over the roof', 'The birds', 'The roof', 'C', 'The birds are the people or things the sentence says something about.', 'medium', 1),
('JSS1', null, 'English Studies', 'Articles', 'Choose the correct phrase.', 'A honest pupil', 'An honest pupil', 'The honest pupil are', 'Honest an pupil', 'B', 'Honest begins with a vowel sound, so an is used before it.', 'medium', 1),
('JSS1', null, 'English Studies', 'Collective nouns', 'A group of cattle is called a ____.', 'flock', 'herd', 'swarm', 'bouquet', 'B', 'A herd is a group of cattle or other large grazing animals.', 'easy', 1),

('JSS1', null, 'Intermediate Science', 'Human body', 'Which organ helps a person breathe by taking oxygen into the body?', 'Kidneys', 'Lungs', 'Stomach', 'Skin', 'B', 'The lungs exchange oxygen and carbon dioxide during breathing.', 'easy', 1),
('JSS1', null, 'Intermediate Science', 'States of matter', 'What is the change from liquid water to water vapour called?', 'Freezing', 'Melting', 'Evaporation', 'Condensation', 'C', 'Evaporation changes a liquid into a gas at its surface.', 'easy', 1),
('JSS1', null, 'Intermediate Science', 'Plant structure', 'Which plant part mainly absorbs water and mineral salts from the soil?', 'Flower', 'Leaf', 'Root', 'Fruit', 'C', 'Roots take in water and dissolved mineral salts from the soil.', 'easy', 1),
('JSS1', null, 'Intermediate Science', 'Force and motion', 'Which action shows that a force can change the motion of an object?', 'A book remains on a desk.', 'A resting ball is kicked and rolls.', 'A stone is grey.', 'Water fills a cup.', 'B', 'The kick applies a force that sets the resting ball in motion.', 'easy', 1),
('JSS1', null, 'Intermediate Science', 'Particles and matter', 'Which statement best describes particles in a solid?', 'They are very far apart and move freely.', 'They are close together and vibrate about fixed positions.', 'They do not exist.', 'They move only when the solid melts.', 'B', 'Solid particles are closely packed and mainly vibrate in fixed positions.', 'medium', 1),
('JSS1', null, 'Intermediate Science', 'Living things and environment', 'In a simple food chain, which organism is usually a producer?', 'Green plant', 'Goat', 'Hawk', 'Mushroom', 'A', 'Green plants make food using sunlight and form the base of many food chains.', 'easy', 1),
('JSS1', null, 'Intermediate Science', 'Laboratory safety', 'What should a learner do if an unknown chemical spills on the laboratory bench?', 'Taste it to identify it.', 'Touch it with bare hands.', 'Tell the teacher and follow safety instructions.', 'Mix it with another chemical.', 'C', 'A learner should alert the teacher and follow the correct spill procedure.', 'easy', 1),
('JSS1', null, 'Intermediate Science', 'Energy and plants', 'Which source of energy is needed by green plants to make food?', 'Moonlight', 'Sunlight', 'Sound', 'Wind alone', 'B', 'Plants use light energy in photosynthesis.', 'easy', 1),

('JSS1', null, 'Digital Technologies', 'Computer components', 'Which computer component carries out instructions and processes data?', 'Monitor', 'Central processing unit', 'Keyboard', 'Loudspeaker', 'B', 'The central processing unit (CPU) processes instructions and data.', 'easy', 1),
('JSS1', null, 'Digital Technologies', 'Input devices', 'Which device is mainly used to enter letters and numbers into a computer?', 'Keyboard', 'Monitor', 'Projector', 'Speaker', 'A', 'A keyboard is an input device for entering text and other commands.', 'easy', 1),
('JSS1', null, 'Digital Technologies', 'Files and folders', 'Why are folders used on a computer?', 'To organise related files', 'To increase the screen brightness', 'To print without a printer', 'To remove the keyboard', 'A', 'Folders help users organise and find related files.', 'easy', 1),
('JSS1', null, 'Digital Technologies', 'Digital safety', 'Which is the safest password practice?', 'Use your first name only.', 'Share your password with classmates.', 'Use a strong password and keep it private.', 'Write the password on a public noticeboard.', 'C', 'A strong private password helps protect an account from unauthorised access.', 'easy', 1),
('JSS1', null, 'Digital Technologies', 'Online safety', 'A stranger online asks for your one-time password. What should you do?', 'Send it immediately.', 'Post it in a group chat.', 'Keep it private and tell a trusted adult.', 'Use it as your username.', 'C', 'One-time passwords are private security codes and should never be shared.', 'easy', 1),
('JSS1', null, 'Digital Technologies', 'Internet tools', 'Which kind of software is used to open and view websites?', 'Web browser', 'Calculator', 'Paint program', 'File compressor', 'A', 'A web browser displays websites and helps users navigate the web.', 'easy', 1),
('JSS1', null, 'Digital Technologies', 'Binary numbers', 'Which two digits are used in the binary number system?', '0 and 1', '1 and 2', '0 and 9', 'A and B', 'A', 'Binary represents values using only the digits 0 and 1.', 'medium', 1),
('JSS1', null, 'Digital Technologies', 'Saving work', 'What should you do to keep changes made to a document?', 'Close the computer without saving.', 'Save the document.', 'Delete the document.', 'Turn off the monitor only.', 'B', 'Saving stores the current changes so they can be opened later.', 'easy', 1),

('JSS1', null, 'Nigerian History', 'Independence', 'In which year did Nigeria gain independence from British rule?', '1957', '1960', '1963', '1970', 'B', 'Nigeria became independent on 1 October 1960.', 'easy', 1),
('JSS1', null, 'Nigerian History', 'Amalgamation', 'Who amalgamated the Northern and Southern Protectorates of Nigeria in 1914?', 'Lord Lugard', 'Herbert Macaulay', 'Nnamdi Azikiwe', 'Abubakar Tafawa Balewa', 'A', 'Frederick Lugard administered the 1914 amalgamation of the protectorates.', 'medium', 1),
('JSS1', null, 'Nigerian History', 'National symbols', 'Who designed the Nigerian national flag?', 'Wole Soyinka', 'Taiwo Akinkunmi', 'Chinua Achebe', 'Ben Enwonwu', 'B', 'Taiwo Akinkunmi designed the Nigerian flag selected in 1959.', 'easy', 1),
('JSS1', null, 'Nigerian History', 'Historical sources', 'Which is an example of an oral source of history?', 'A recorded family story told by an elder', 'A modern traffic light', 'A new school uniform', 'A weather forecast', 'A', 'Oral history is information passed on through spoken accounts and traditions.', 'easy', 1),
('JSS1', null, 'Nigerian History', 'Early Nigerian societies', 'The Nok culture is especially known for which archaeological objects?', 'Terracotta human figures', 'Steam engines', 'Printed newspapers', 'Glass skyscrapers', 'A', 'Nok archaeological sites are known for ancient terracotta sculptures.', 'medium', 1),
('JSS1', null, 'Nigerian History', 'Early Nigerian societies', 'Which ancient Nigerian town is well known for naturalistic bronze and terracotta art?', 'Ile-Ife', 'Calabar', 'Jos', 'Minna', 'A', 'Ile-Ife is renowned for its important historical bronze and terracotta works.', 'medium', 1),
('JSS1', null, 'Nigerian History', 'Government', 'Who was Nigeria’s first Prime Minister after independence?', 'Nnamdi Azikiwe', 'Abubakar Tafawa Balewa', 'Yakubu Gowon', 'Olusegun Obasanjo', 'B', 'Abubakar Tafawa Balewa served as Prime Minister at independence.', 'medium', 1),
('JSS1', null, 'Nigerian History', 'National capital', 'Which city became Nigeria’s capital in 1991?', 'Lagos', 'Kano', 'Abuja', 'Ibadan', 'C', 'The federal capital moved from Lagos to Abuja in 1991.', 'easy', 1),

('JSS1', null, 'Business Studies', 'Needs and wants', 'Which item is a basic need?', 'Clean drinking water', 'A second television for entertainment', 'A gold necklace', 'A video game', 'A', 'Water is essential for life, while the other items are wants.', 'easy', 1),
('JSS1', null, 'Business Studies', 'Trade', 'What does trade mainly involve?', 'Buying and selling goods or services', 'Planting only ornamental flowers', 'Measuring rainfall', 'Writing a poem', 'A', 'Trade is the buying and selling of goods and services.', 'easy', 1),
('JSS1', null, 'Business Studies', 'Entrepreneurship', 'Who is an entrepreneur?', 'A person who organises a business and takes its risks', 'A person who only buys goods for personal use', 'A person who collects taxes for government', 'A person who studies rocks', 'A', 'An entrepreneur organises resources to start or run a business and accepts business risks.', 'medium', 1),
('JSS1', null, 'Business Studies', 'Business records', 'What does a receipt usually provide?', 'Evidence that a payment or purchase was made', 'Permission to drive a bus', 'A list of school subjects', 'A weather report', 'A', 'A receipt records a transaction and can show that payment was made.', 'easy', 1),
('JSS1', null, 'Business Studies', 'Capital', 'In a small business, what is capital?', 'Resources or money used to start and run the business', 'The amount of rain in a town', 'A customer complaint', 'The business signboard only', 'A', 'Capital includes money and other resources invested in a business.', 'easy', 1),
('JSS1', null, 'Business Studies', 'Saving', 'What does it mean to save part of your income?', 'Keep some money for future use', 'Spend all the money immediately', 'Borrow money from every customer', 'Hide business records', 'A', 'Saving means setting aside money instead of spending it all now.', 'easy', 1),
('JSS1', null, 'Business Studies', 'Consumers', 'Who is a consumer?', 'The final user of a good or service', 'Only the person who manufactures a product', 'The person who writes a school timetable', 'A person who repairs roads', 'A', 'A consumer uses or buys goods and services for use.', 'easy', 1),
('JSS1', null, 'Business Studies', 'Profit and loss', 'A trader buys a book for ₦800 and sells it for ₦1,000. What is the profit?', '₦100', '₦200', '₦800', '₦1,800', 'B', 'Profit = selling price − cost price = ₦1,000 − ₦800 = ₦200.', 'medium', 1),

('JSS1', null, 'Cultural and Creative Arts', 'Elements of art', 'Which set contains the three traditional primary colours used in basic colour mixing?', 'Red, yellow and blue', 'Green, orange and purple', 'Black, white and grey', 'Pink, brown and gold', 'A', 'In basic traditional colour mixing, red, yellow and blue are treated as primary colours.', 'easy', 1),
('JSS1', null, 'Cultural and Creative Arts', 'Colour mixing', 'Which colour is made by mixing blue and yellow paint?', 'Orange', 'Green', 'Purple', 'Brown', 'B', 'Blue and yellow are mixed to make green in basic paint colour mixing.', 'easy', 1),
('JSS1', null, 'Cultural and Creative Arts', 'Elements of music', 'In music, what is a steady pattern of beats called?', 'Rhythm', 'Texture', 'Shade', 'Perspective', 'A', 'Rhythm is the organised pattern of sounds and beats over time.', 'easy', 1),
('JSS1', null, 'Cultural and Creative Arts', 'Art materials', 'Which material is commonly used to make a collage?', 'Cut or torn pieces of paper', 'Only clear drinking water', 'A tuning fork alone', 'A ruler with no other material', 'A', 'A collage is made by arranging and attaching materials such as paper pieces to a surface.', 'easy', 1),
('JSS1', null, 'Cultural and Creative Arts', 'Drama', 'What is a script in a drama?', 'The written words and directions for a performance', 'The costume worn by the audience', 'The stage floor only', 'The ticket sold at the entrance', 'A', 'A script contains dialogue and may include directions for performers.', 'easy', 1),
('JSS1', null, 'Cultural and Creative Arts', 'Nigerian arts', 'Which material is traditionally associated with many Benin Kingdom artworks?', 'Bronze', 'Ice', 'Rubber foam', 'Paper mache only', 'A', 'Benin is widely known for its historical bronze plaques and sculptures.', 'medium', 1),
('JSS1', null, 'Cultural and Creative Arts', 'Drawing', 'In drawing, what is a line?', 'A mark that can show direction or outline', 'A type of musical instrument', 'A colour made only from water', 'A finished clay pot', 'A', 'Lines can define edges, outlines, directions and patterns in artwork.', 'easy', 1),
('JSS1', null, 'Cultural and Creative Arts', 'Art appreciation', 'What should a learner do when giving a respectful comment about a classmate’s artwork?', 'Describe what is visible and give a helpful reason', 'Mock the artist', 'Damage the artwork', 'Claim every artwork must look identical', 'A', 'Respectful art appreciation describes features and gives constructive, reasoned feedback.', 'easy', 1)
on conflict do nothing;
