-- SS1 Science stream starter batch: five newly authored questions per
-- supported Science subject. Category uses the question-bank stream key.
insert into public.question_bank (
  level, category, subject, topic, question,
  option_a, option_b, option_c, option_d, correct_answer,
  explanation, difficulty, marks, is_active
) values
('SS1', 'science', 'Biology', 'Cell structure', 'Which cell structure selectively controls substances entering and leaving a cell?', 'Ribosome', 'Cell membrane', 'Nucleolus', 'Vacuole', 'B', 'The cell membrane is selectively permeable and regulates exchange with the surroundings.', 'easy', '1', 'true'),
('SS1', 'science', 'Biology', 'Cell organisation', 'Which sequence shows levels of organisation from simplest to most complex?', 'Organ → cell → tissue → system', 'Tissue → cell → system → organ', 'Cell → tissue → organ → system', 'Cell → organ → tissue → system', 'C', 'Similar cells form tissues; tissues form organs, and organs work together in systems.', 'easy', '1', 'true'),
('SS1', 'science', 'Biology', 'Nutrition in plants', 'During photosynthesis, which raw material supplies the carbon atoms used to form glucose?', 'Oxygen from the air', 'Nitrogen from the soil', 'Chlorophyll from the leaf', 'Carbon dioxide from the air', 'D', 'Carbon dioxide provides the carbon that is incorporated into carbohydrate during photosynthesis.', 'medium', '1', 'true'),
('SS1', 'science', 'Biology', 'Transport in plants', 'Which plant tissue transports manufactured sugars from leaves to other parts?', 'Phloem', 'Xylem', 'Epidermis', 'Cambium only', 'A', 'Phloem translocates sugars and other organic substances through the plant.', 'easy', '1', 'true'),
('SS1', 'science', 'Biology', 'Cell respiration', 'In which organelle does most aerobic respiration in a eukaryotic cell take place?', 'Chloroplast', 'Mitochondrion', 'Golgi apparatus', 'Vacuole', 'B', 'Mitochondria are the main sites of aerobic respiration and ATP production in eukaryotic cells.', 'medium', '1', 'true'),

('SS1', 'science', 'Chemistry', 'Atomic structure', 'An atom has atomic number 11 and mass number 23. How many neutrons are in its nucleus?', '12', '11', '23', '34', 'A', 'Neutrons = mass number − atomic number = 23 − 11 = 12.', 'easy', '1', 'true'),
('SS1', 'science', 'Chemistry', 'Elements and compounds', 'Which formula represents a molecule containing two nitrogen atoms?', 'N', 'N₂', '2N₂', 'NO₂', 'B', 'The subscript 2 in N₂ indicates two nitrogen atoms bonded in one molecule.', 'easy', '1', 'true'),
('SS1', 'science', 'Chemistry', 'Mixtures', 'Which method is most suitable for obtaining salt crystals from a salt solution?', 'Use a magnet to remove the salt', 'Filter the solution through dry sand', 'Evaporate some water and allow the solution to crystallise', 'Separate the salt using a separating funnel', 'C', 'Concentrating the solution and allowing it to cool or evaporate forms salt crystals.', 'medium', '1', 'true'),
('SS1', 'science', 'Chemistry', 'Chemical bonding', 'What type of bond forms when two atoms share a pair of electrons?', 'Ionic bond', 'Metallic bond', 'Hydrogen bond', 'Covalent bond', 'D', 'A covalent bond forms when atoms share electron pairs.', 'medium', '1', 'true'),
('SS1', 'science', 'Chemistry', 'Acids and bases', 'Which salt is formed when hydrochloric acid is completely neutralised by sodium hydroxide?', 'Sodium chloride', 'Sodium carbonate', 'Calcium chloride', 'Sodium sulfate', 'A', 'Hydrochloric acid reacts with sodium hydroxide to form sodium chloride and water.', 'medium', '1', 'true'),

('SS1', 'science', 'Physics', 'Measurement', 'Which instrument is most appropriate for measuring the internal diameter of a narrow tube accurately?', 'Metre rule', 'Stopwatch', 'Spring balance', 'Vernier calipers', 'D', 'Vernier calipers have internal jaws designed for measuring internal diameters.', 'easy', '1', 'true'),
('SS1', 'science', 'Physics', 'Motion', 'A vehicle travels 150 m in 10 s at constant speed. What is its speed?', '15 m/s', '1.5 m/s', '150 m/s', '1,500 m/s', 'A', 'Speed = distance ÷ time = 150 m ÷ 10 s = 15 m/s.', 'easy', '1', 'true'),
('SS1', 'science', 'Physics', 'Force', 'A 4 kg object accelerates at 3 m/s². What resultant force acts on it?', '1.3 N', '12 N', '7 N', '24 N', 'B', 'By Newton’s second law, F = ma = 4 × 3 = 12 N.', 'medium', '1', 'true'),
('SS1', 'science', 'Physics', 'Energy', 'A 2 kg bag is lifted vertically through 5 m. Taking g = 10 m/s², how much gravitational potential energy does it gain?', '10 J', '25 J', '100 J', '250 J', 'C', 'Gain in potential energy = mgh = 2 × 10 × 5 = 100 J.', 'medium', '1', 'true'),
('SS1', 'science', 'Physics', 'Electricity', 'A 6 Ω resistor is connected across a 12 V supply. What current flows?', '0.5 A', '6 A', '72 A', '2 A', 'D', 'Ohm’s law gives I = V ÷ R = 12 ÷ 6 = 2 A.', 'medium', '1', 'true'),

('SS1', 'science', 'Agriculture', 'Soil science', 'Which soil property mainly describes the proportion of sand, silt and clay particles?', 'Soil pH', 'Soil texture', 'Soil colour', 'Soil temperature', 'B', 'Soil texture is determined by the relative sizes and proportions of mineral particles.', 'easy', '1', 'true'),
('SS1', 'science', 'Agriculture', 'Soil fertility', 'Which nutrient is especially associated with leafy vegetative growth in crops?', 'Phosphorus', 'Potassium', 'Nitrogen', 'Calcium', 'C', 'Nitrogen supports chlorophyll formation and vigorous vegetative growth.', 'easy', '1', 'true'),
('SS1', 'science', 'Agriculture', 'Crop production', 'Why is a seedbed watered gently after sowing small seeds?', 'To prevent the seeds from absorbing water', 'To make the soil permanently waterlogged', 'To expose the seeds to direct sunlight', 'To avoid washing or displacing the seeds', 'D', 'Gentle watering supplies moisture while reducing erosion and movement of small seeds.', 'easy', '1', 'true'),
('SS1', 'science', 'Agriculture', 'Farm tools', 'Which tool is best suited to loosening soil and making planting holes on a small farm?', 'Hoe', 'Cutlass', 'Sickle', 'Wheelbarrow', 'A', 'A hoe is commonly used for loosening soil, making ridges and preparing planting holes.', 'easy', '1', 'true'),
('SS1', 'science', 'Agriculture', 'Farm records', 'A farmer records dates of planting, input use and harvest quantities. What is the main purpose?', 'To replace all field observation', 'To support planning and evaluate farm performance', 'To guarantee a fixed market price', 'To prevent crops from needing labour', 'B', 'Accurate farm records help the farmer compare results and make informed production decisions.', 'medium', '1', 'true'),

('SS1', 'science', 'Further Mathematics', 'Sets', 'If A = {1, 2, 3, 4} and B = {3, 4, 5}, what is A ∩ B?', '{1, 2, 3, 4, 5}', '{1, 2}', '{3, 4}', '{5}', 'C', 'The intersection contains elements common to both sets: 3 and 4.', 'easy', '1', 'true'),
('SS1', 'science', 'Further Mathematics', 'Functions', 'For f(x) = 2x² − 3, find f(2).', '1', '8', '11', '5', 'D', 'f(2) = 2(2²) − 3 = 8 − 3 = 5.', 'easy', '1', 'true'),
('SS1', 'science', 'Further Mathematics', 'Quadratic equations', 'Which are the roots of x² − 7x + 10 = 0?', '2 and 5', '1 and 10', '−2 and −5', '−1 and 10', 'A', 'Factorising gives (x − 2)(x − 5) = 0, so the roots are 2 and 5.', 'medium', '1', 'true'),
('SS1', 'science', 'Further Mathematics', 'Sequences', 'An arithmetic sequence has first term 7 and common difference 4. What is its 10th term?', '39', '43', '44', '47', 'B', 'The 10th term is 7 + 9 × 4 = 43.', 'medium', '1', 'true'),
('SS1', 'science', 'Further Mathematics', 'Logarithms', 'Evaluate log₁₀ 1000.', '2', '10', '3', '100', 'C', 'Since 10³ = 1000, log₁₀ 1000 = 3.', 'easy', '1', 'true'),

('SS1', 'science', 'Physical Education', 'Physical fitness', 'Which component of fitness is most directly measured by the distance covered in a timed long-distance run?', 'Flexibility', 'Reaction time', 'Explosive strength', 'Cardiorespiratory endurance', 'D', 'A timed distance run primarily assesses the ability of the heart and lungs to sustain activity.', 'easy', '1', 'true'),
('SS1', 'science', 'Physical Education', 'Training principles', 'Why should an athlete increase training load gradually?', 'To allow adaptation and reduce the risk of injury', 'To eliminate the need for recovery', 'To make every session maximal', 'To prevent improvement in performance', 'A', 'Progressive increases give the body time to adapt safely to training demands.', 'medium', '1', 'true'),
('SS1', 'science', 'Physical Education', 'Movement skills', 'In a relay race, what most directly helps a team make a legal, efficient baton exchange?', 'Changing runners after the finish line', 'A clear exchange zone routine and communication', 'Holding the baton with two hands throughout', 'Throwing the baton to the next runner', 'B', 'Practised timing and communication support a controlled exchange within the marked zone.', 'easy', '1', 'true'),
('SS1', 'science', 'Physical Education', 'First aid in sport', 'A player twists an ankle and develops swelling. What is the safest immediate action?', 'Continue playing to keep the joint warm.', 'Massage the injury forcefully.', 'Stop activity and seek appropriate first aid assessment.', 'Apply heat and return to play immediately.', 'C', 'Stop activity and arrange assessment; further treatment should follow trained first-aid guidance.', 'medium', '1', 'true'),
('SS1', 'science', 'Physical Education', 'Sportsmanship', 'An official makes a decision a player disagrees with. Which response demonstrates sportsmanship?', 'Insult the official loudly.', 'Leave the field without permission.', 'Retaliate against an opponent.', 'Raise a respectful query through the team captain when appropriate.', 'D', 'Respectful communication and use of the proper process maintain fair play.', 'easy', '1', 'true'),

('SS1', 'science', 'Health Education', 'Personal health', 'Which habit most directly reduces the spread of many infectious diseases after using the toilet?', 'Washing hands thoroughly with soap and clean water', 'Sharing a hand towel without washing it', 'Taking antibiotics without advice', 'Avoiding all physical exercise', 'A', 'Handwashing removes pathogens that may otherwise be transferred to food, surfaces or people.', 'easy', '1', 'true'),
('SS1', 'science', 'Health Education', 'Nutrition', 'Which nutrient is needed for growth and repair of body tissues?', 'Water only', 'Protein', 'Dietary fibre only', 'Vitamin C only', 'B', 'Proteins supply amino acids used to build and repair body tissues.', 'easy', '1', 'true'),
('SS1', 'science', 'Health Education', 'Communicable diseases', 'Which action lowers the risk of malaria transmission around a home?', 'Allowing stagnant water to collect in open containers', 'Sharing sleeping spaces with open windows only', 'Using insecticide-treated nets and removing mosquito breeding sites', 'Keeping refuse in uncovered heaps', 'C', 'Treated nets reduce mosquito bites, while removing standing water limits breeding sites.', 'medium', '1', 'true'),
('SS1', 'science', 'Health Education', 'Mental health', 'A learner feels persistently overwhelmed and unable to cope. What is an appropriate first step?', 'Keep the problem secret from every trusted person.', 'Stop eating and sleeping until school improves.', 'Use another person’s medication.', 'Seek support from a trusted adult or qualified health professional.', 'D', 'Trusted adults and qualified professionals can help assess the situation and connect the learner to suitable support.', 'medium', '1', 'true'),
('SS1', 'science', 'Health Education', 'Substance use', 'Why can sharing needles increase the risk of blood-borne infections?', 'Blood on a used needle can pass infectious agents between people.', 'Needles remove all pathogens from blood.', 'Infections spread only through clean water.', 'A needle changes a person’s blood group.', 'A', 'Contaminated blood remaining on equipment can transmit infections when equipment is shared.', 'hard', '2', 'true'),

('SS1', 'science', 'Foods & Nutrition', 'Nutrients', 'Which nutrient group includes butter and cooking oil and provides a concentrated source of energy?', 'Proteins', 'Mineral salts', 'Water-soluble vitamins', 'Fats and oils', 'D', 'Butter and cooking oils are fats; fats provide concentrated energy and support other body functions.', 'easy', '1', 'true'),
('SS1', 'science', 'Foods & Nutrition', 'Food hygiene', 'Why should raw poultry be kept separate from ready-to-eat food during preparation?', 'To prevent cross-contamination by microorganisms', 'To make the poultry cook more quickly', 'To increase the salt content of both foods', 'To stop vegetables from containing water', 'A', 'Separating raw poultry prevents pathogens from contaminating food that will not be cooked again.', 'easy', '1', 'true'),
('SS1', 'science', 'Foods & Nutrition', 'Cooking methods', 'Which cooking method uses hot water or steam and usually requires little added fat?', 'Deep-frying', 'Boiling', 'Roasting', 'Grilling over an open flame', 'B', 'Boiling cooks food in hot water; steaming uses hot vapour, and neither requires frying fat.', 'easy', '1', 'true'),
('SS1', 'science', 'Foods & Nutrition', 'Meal planning', 'A balanced meal for an active student should generally include which combination?', 'Only a sugary drink and sweets', 'Only fried snacks', 'A staple carbohydrate, a protein source and vegetables or fruit', 'Only meat with no other food group', 'C', 'Combining staple energy foods, protein and fruit or vegetables improves dietary variety.', 'medium', '1', 'true'),
('SS1', 'science', 'Foods & Nutrition', 'Food preservation', 'How does refrigeration slow food spoilage?', 'It removes all water from food instantly.', 'It sterilises every food permanently.', 'It turns proteins into carbohydrates.', 'It lowers temperature and slows the growth of many microorganisms.', 'D', 'Low temperature slows many microbial and chemical processes, though refrigeration does not sterilise food.', 'medium', '1', 'true'),

('SS1', 'science', 'Geography', 'Map skills', 'On a map with scale 1:50,000, two towns are 4 cm apart. What is their ground distance?', '2 km', '0.5 km', '20 km', '200 km', 'A', '4 cm × 50,000 = 200,000 cm, which equals 2 km.', 'medium', '1', 'true'),
('SS1', 'science', 'Geography', 'Weather and climate', 'On a weather map, what does a closely spaced set of isobars usually indicate?', 'Light winds', 'Strong winds', 'High humidity everywhere', 'A fixed temperature', 'B', 'Closely spaced isobars show a steep pressure gradient, which is commonly associated with stronger winds.', 'medium', '1', 'true'),
('SS1', 'science', 'Geography', 'Climate and seasons', 'How does Earth’s axial tilt contribute to seasonal differences between hemispheres?', 'It changes Earth’s distance from the Moon each month.', 'It stops Earth rotating during winter.', 'It changes the angle and duration of sunlight received through the year.', 'It makes both hemispheres receive identical sunlight all year.', 'C', 'As Earth orbits the Sun, axial tilt changes solar angle and day length by season and hemisphere.', 'medium', '1', 'true'),
('SS1', 'science', 'Geography', 'Rocks', 'Which rock type forms when sediments are deposited, compacted and cemented?', 'Igneous', 'Metamorphic', 'Volcanic glass only', 'Sedimentary', 'D', 'Sedimentary rocks develop from accumulated sediments that become compacted and cemented.', 'medium', '1', 'true'),
('SS1', 'science', 'Geography', 'Weathering and erosion', 'Which statement distinguishes erosion from weathering?', 'Erosion moves broken material; weathering breaks rock down in place.', 'Weathering moves soil only; erosion forms clouds.', 'Both terms mean exactly the same process.', 'Erosion occurs only underground.', 'A', 'Weathering breaks down rock, while erosion involves removal and transport of material.', 'medium', '1', 'true'),

('SS1', 'science', 'Technical Drawing', 'Drawing instruments', 'Which instrument is designed to draw a circle or arc with a chosen radius?', 'Protractor', 'T-square', 'Set square', 'Compass', 'D', 'A compass holds a point and pencil at a fixed separation to draw circles and arcs.', 'easy', '1', 'true'),
('SS1', 'science', 'Technical Drawing', 'Scales', 'A component is 80 mm long. On a drawing made at scale 1:4, how long should it be drawn?', '20 mm', '10 mm', '80 mm', '320 mm', 'A', 'At 1:4, drawing length = actual length ÷ 4 = 80 ÷ 4 = 20 mm.', 'easy', '1', 'true'),
('SS1', 'science', 'Technical Drawing', 'Orthographic projection', 'In first-angle orthographic projection, where is the top view placed relative to the front view?', 'Above it', 'Below it', 'To its right in every case', 'Inside the front view', 'B', 'In first-angle projection, the top view is placed below the front view.', 'medium', '1', 'true'),
('SS1', 'science', 'Technical Drawing', 'Line conventions', 'Which line type is normally used to show an edge that is hidden from view?', 'Continuous thick line', 'Continuous thin dimension line', 'Dashed line', 'Freehand break line only', 'C', 'Short-dashed lines conventionally represent hidden edges in technical drawings.', 'medium', '1', 'true'),
('SS1', 'science', 'Technical Drawing', 'Dimensioning', 'Why should extension lines usually extend slightly beyond a dimension line?', 'To change the scale of the object', 'To indicate a hidden surface', 'To mark the centre of every circle', 'To show clearly which feature the dimension refers to', 'D', 'Extension lines connect the measured feature to the dimension line for clear interpretation.', 'easy', '1', 'true')
on conflict do nothing;
