-- SS1 Commercial stream starter batch: five questions for each supported
-- subject. The category value matches the exam RPC's stream key.
insert into public.question_bank (
  level, category, subject, topic, question,
  option_a, option_b, option_c, option_d, correct_answer,
  explanation, difficulty, marks, is_active
) values
('SS1', 'commercial', 'Accounting', 'Accounting equation', 'A business has assets of ₦780,000 and liabilities of ₦265,000. What is the owner’s capital?', '₦525,000', '₦515,000', '₦780,000', '₦1,045,000', 'B', 'Capital = assets − liabilities = ₦780,000 − ₦265,000 = ₦515,000.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Accounting', 'Source documents', 'Which source document does a seller normally issue to show the details and amount due for goods supplied on credit?', 'Receipt', 'Cheque counterfoil', 'Invoice', 'Statement of account', 'C', 'An invoice lists goods supplied and the amount the buyer is expected to pay.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Accounting', 'Double-entry bookkeeping', 'A trader pays ₦18,000 cash for stationery. Which accounts are debited and credited?', 'Debit cash; credit stationery', 'Debit capital; credit sales', 'Debit purchases; credit debtor', 'Debit stationery; credit cash', 'D', 'Stationery expense increases and is debited; cash decreases and is credited.', 'medium', '1', 'true'),
('SS1', 'commercial', 'Accounting', 'Trial balance', 'Which error may not cause the trial balance totals to disagree?', 'Posting a transaction to the wrong account but on the correct side and for the correct amount', 'Entering only the debit part of a transaction', 'Adding the debit column incorrectly', 'Posting different amounts to the debit and credit sides', 'A', 'An error of commission can leave debit and credit totals equal even though the account is wrong.', 'hard', '2', 'true'),
('SS1', 'commercial', 'Accounting', 'Depreciation', 'Equipment cost ₦240,000 and is depreciated at 10% per year using the straight-line method with no residual value. What is one year’s depreciation?', '₦2,400', '₦24,000', '₦12,000', '₦216,000', 'B', 'Annual depreciation = 10% × ₦240,000 = ₦24,000.', 'medium', '1', 'true'),

('SS1', 'commercial', 'Commerce', 'Trade', 'Which activity is an example of home trade?', 'A Nigerian firm sells goods to a buyer in Ghana.', 'A ship carries cocoa from Nigeria to Europe.', 'A company imports machinery from Japan.', 'A Kano wholesaler sells textiles to a retailer in Lagos.', 'D', 'Home trade takes place within the borders of one country.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Commerce', 'Channels of distribution', 'Which sequence shows the usual channel for goods sold through a wholesaler and retailer?', 'Producer → wholesaler → retailer → consumer', 'Producer → retailer → wholesaler → consumer', 'Consumer → producer → retailer → wholesaler', 'Wholesaler → producer → consumer → retailer', 'A', 'Wholesalers buy from producers and supply retailers, who sell to final consumers.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Commerce', 'Warehousing', 'How does warehousing assist trade?', 'It sets the national exchange rate.', 'It stores goods until they are needed for sale or use.', 'It replaces all transport services.', 'It guarantees that no goods can be damaged.', 'B', 'Warehouses hold goods and help balance supply with demand over time.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Commerce', 'Insurance', 'In insurance, what is a premium?', 'The total value of every asset owned by an insurer', 'A guaranteed profit paid to a policyholder', 'The amount paid by the insured for cover', 'The document used to order stock', 'C', 'A premium is the price paid for an insurance policy or cover.', 'medium', '1', 'true'),
('SS1', 'commercial', 'Commerce', 'International trade', 'A Nigerian importer pays a foreign supplier in another currency. Which document commonly provides evidence of the amount and terms charged for the goods?', 'Delivery note issued by the local retailer', 'Petty cash voucher', 'Staff attendance register', 'Commercial invoice', 'D', 'A commercial invoice records the goods, prices and terms of the international sale.', 'medium', '1', 'true'),

('SS1', 'commercial', 'Marketing', 'Marketing concepts', 'A firm studies customers’ needs before designing a product. Which marketing idea does this demonstrate?', 'Production orientation', 'Sales orientation only', 'Customer orientation', 'Product disposal', 'C', 'Customer-oriented marketing begins by understanding needs and then creating suitable value.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Marketing', 'Marketing mix', 'A company lowers the price of a product for a launch promotion. Which element of the marketing mix is being changed?', 'Product', 'Place', 'Promotion', 'Price', 'D', 'Price is the amount customers pay; a temporary price reduction changes this element.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Marketing', 'Market research', 'Why might a business test a questionnaire with a small group before using it widely?', 'To identify unclear or biased questions', 'To guarantee that every respondent agrees', 'To avoid collecting any customer information', 'To make the product more expensive', 'A', 'A pilot can reveal confusing questions and improve the quality of responses.', 'medium', '1', 'true'),
('SS1', 'commercial', 'Marketing', 'Product life cycle', 'A product’s sales have begun to fall as newer alternatives attract buyers. Which stage is it most likely entering?', 'Introduction', 'Decline', 'Growth', 'Maturity', 'B', 'Decline is marked by falling sales, often as demand shifts to alternatives.', 'medium', '1', 'true'),
('SS1', 'commercial', 'Marketing', 'Consumer behaviour', 'A customer compares price, quality and warranty before buying a phone. This is an example of what?', 'Post-purchase disposal', 'Impulse buying without evaluation', 'Evaluating alternatives', 'Market segmentation by a producer', 'C', 'The buyer is assessing competing choices against decision criteria before purchase.', 'hard', '2', 'true'),

('SS1', 'commercial', 'Economics', 'Scarcity and choice', 'A student has ₦4,000 and chooses a textbook instead of a concert ticket. The next-best option forgone is the student’s what?', 'Fixed cost', 'Total revenue', 'Opportunity cost', 'Sunk benefit', 'C', 'Opportunity cost is the value of the next-best alternative given up when making a choice.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Economics', 'Demand', 'If the price of a normal good falls, what is generally expected, other factors unchanged?', 'Demand falls to zero.', 'Supply must also fall.', 'Consumers stop considering substitutes.', 'Quantity demanded rises.', 'D', 'The law of demand states that lower price generally increases quantity demanded, ceteris paribus.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Economics', 'Supply', 'A new machine lowers the cost of producing bread. What is the likely effect on the supply curve, other factors unchanged?', 'A rightward shift of supply', 'A movement up along the existing supply curve', 'A leftward shift of supply', 'No possible change in supply', 'A', 'Lower production costs make producers willing and able to supply more at each price, shifting supply right.', 'medium', '1', 'true'),
('SS1', 'commercial', 'Economics', 'Production', 'Which factor of production receives rent as its factor reward?', 'Labour', 'Land', 'Capital', 'Entrepreneurship', 'B', 'Rent is the traditional reward for the use of land and natural resources.', 'easy', '1', 'true'),
('SS1', 'commercial', 'Economics', 'Elasticity of demand', 'The price of a product rises by 10% and its quantity demanded falls by 20%. What is the absolute value of price elasticity of demand?', '0.5', '1', '2', '10', 'C', 'Elasticity = percentage change in quantity ÷ percentage change in price = 20% ÷ 10% = 2.', 'hard', '2', 'true')
on conflict do nothing;
