-- SS1 Arts stream starter batch: five questions for every supported Arts
-- subject. Category matches the question-bank stream key, 'arts'.
insert into public.question_bank (
  level, category, subject, topic, question,
  option_a, option_b, option_c, option_d, correct_answer,
  explanation, difficulty, marks, is_active
) values
('SS1', 'arts', 'Nigerian History', 'Pre-colonial states', 'Which city served as a major political centre of the old Oyo Empire?', 'Calabar', 'Oyo-Ile', 'Aba', 'Yenagoa', 'B', 'Oyo-Ile was the principal capital of the Oyo Empire before its decline.', 'easy', '1', 'true'),
('SS1', 'arts', 'Nigerian History', 'Sources of history', 'A dated letter written by a participant during an event is generally what type of historical source?', 'Tertiary source', 'Fictional source', 'Primary source', 'Oral source only', 'C', 'A contemporary document created by a participant is a primary source for the event.', 'easy', '1', 'true'),
('SS1', 'arts', 'Nigerian History', 'Trans-Saharan trade', 'Which pair of goods was commonly exchanged across the Sahara between North and West Africa?', 'Petroleum and cocoa', 'Rubber tyres and tea', 'Tin cans and rice', 'Salt and gold', 'D', 'Salt from North Africa and gold from West Africa were important trans-Saharan trade goods.', 'easy', '1', 'true'),
('SS1', 'arts', 'Nigerian History', 'Colonial administration', 'What was a central feature of British indirect rule in Northern Nigeria?', 'Using existing emirs and institutions under colonial supervision', 'Abolishing all local authorities immediately', 'Allowing each town to conduct foreign policy', 'Replacing every local court with elected councils', 'A', 'Indirect rule governed through existing authorities while colonial officers supervised the system.', 'medium', '1', 'true'),
('SS1', 'arts', 'Nigerian History', 'Nationalism', 'Which development helped Nigerian nationalist ideas reach a wider reading public in the early twentieth century?', 'Closure of all schools', 'Growth of locally produced newspapers', 'End of coastal trade', 'Introduction of television broadcasting', 'B', 'Newspapers provided a medium for political discussion, criticism and nationalist advocacy.', 'medium', '1', 'true'),

('SS1', 'arts', 'Government', 'Forms of government', 'In a federal system, constitutional powers are divided between which levels?', 'The ruling party and the opposition only', 'National and subnational governments', 'The police and the armed forces only', 'Courts and private companies', 'B', 'Federalism constitutionally shares authority between a central government and constituent units.', 'easy', '1', 'true'),
('SS1', 'arts', 'Government', 'Separation of powers', 'Which institution primarily makes laws at the federal level in Nigeria?', 'Federal Executive Council', 'Supreme Court', 'National Assembly', 'Independent National Electoral Commission', 'C', 'The National Assembly is the federal legislature and exercises law-making functions.', 'easy', '1', 'true'),
('SS1', 'arts', 'Government', 'Rule of law', 'What does equality before the law mean?', 'Only public officers must obey the law.', 'Judges may ignore written law whenever they wish.', 'Citizens can choose which court orders to obey.', 'The law applies to people without arbitrary privilege or exemption.', 'D', 'The rule of law requires legal rules to apply fairly rather than arbitrarily.', 'medium', '1', 'true'),
('SS1', 'arts', 'Government', 'Political participation', 'Which is a lawful way for citizens to influence a public policy decision?', 'Submit a petition to the appropriate public body.', 'Threaten elected representatives.', 'Destroy public records.', 'Prevent others from attending a meeting.', 'A', 'Petitions are a lawful means of presenting views or requests to public authorities.', 'easy', '1', 'true'),
('SS1', 'arts', 'Government', 'Elections', 'Why are secret ballots used in elections?', 'To allow officials to change votes later', 'To help voters choose without public disclosure of their vote', 'To remove the need to count ballots', 'To prevent eligible citizens from voting', 'B', 'A secret ballot protects voter privacy and reduces intimidation or coercion.', 'medium', '1', 'true'),

('SS1', 'arts', 'Christian Religious Studies', 'Old Testament', 'According to the book of Genesis, who led the Israelites out of Egypt?', 'David', 'Solomon', 'Nehemiah', 'Moses', 'D', 'The Exodus narrative presents Moses as the leader who brought the Israelites out of Egypt.', 'easy', '1', 'true'),
('SS1', 'arts', 'Christian Religious Studies', 'Old Testament', 'Which covenant sign in Genesis is associated with God’s promise to Noah?', 'Rainbow', 'Olive branch', 'Stone tablets', 'Burning bush', 'A', 'In Genesis, the rainbow is given as the sign of the covenant with Noah.', 'easy', '1', 'true'),
('SS1', 'arts', 'Christian Religious Studies', 'New Testament', 'In the parable of the Good Samaritan, which person helped the injured traveller?', 'A tax collector', 'A Samaritan', 'A Roman soldier', 'A fisherman', 'B', 'The Samaritan stops, cares for the injured man and arranges further help.', 'easy', '1', 'true'),
('SS1', 'arts', 'Christian Religious Studies', 'Teachings of Jesus', 'Which attitude is emphasised in the Beatitude “Blessed are the merciful”?', 'Seeking revenge quickly', 'Pursuing wealth above all else', 'Showing compassion and forgiveness', 'Avoiding every act of service', 'C', 'Mercy involves compassion and a willingness to forgive.', 'medium', '1', 'true'),
('SS1', 'arts', 'Christian Religious Studies', 'Early church', 'According to Acts, what event is associated with the disciples receiving the Holy Spirit in Jerusalem?', 'Passover in Egypt', 'The rebuilding of the temple', 'The journey to Jericho', 'Pentecost', 'D', 'Acts describes the disciples receiving the Holy Spirit on the day of Pentecost.', 'medium', '1', 'true'),

('SS1', 'arts', 'Islamic Studies', 'Foundations of Islam', 'How many pillars of Islam are traditionally identified?', 'Three', 'Four', 'Six', 'Five', 'D', 'The five pillars are the testimony of faith, prayer, zakat, fasting in Ramadan and Hajj for those able.', 'easy', '1', 'true'),
('SS1', 'arts', 'Islamic Studies', 'Qur’an', 'In which language was the Qur’an first revealed?', 'Arabic', 'Persian', 'Hebrew', 'Greek', 'A', 'The Qur’an was revealed in Arabic, the language of its original recitation.', 'easy', '1', 'true'),
('SS1', 'arts', 'Islamic Studies', 'Worship', 'How many obligatory daily prayers are observed in Islam?', 'Three', 'Five', 'Four', 'Seven', 'B', 'Muslims observe five obligatory prayers each day.', 'easy', '1', 'true'),
('SS1', 'arts', 'Islamic Studies', 'Zakat', 'What is a central social purpose of zakat?', 'To replace every form of voluntary charity', 'To require every person to give the same fixed sum', 'To support eligible people and promote responsibility toward wealth', 'To pay for private entertainment only', 'C', 'Zakat is an obligatory form of almsgiving with defined recipients and social responsibilities.', 'medium', '1', 'true'),
('SS1', 'arts', 'Islamic Studies', 'Fasting', 'Which month is observed for the obligatory fast by Muslims who are able?', 'Muharram', 'Rajab', 'Dhul-Hijjah', 'Ramadan', 'D', 'Fasting during Ramadan is one of the pillars of Islam for Muslims able to observe it.', 'easy', '1', 'true'),

('SS1', 'arts', 'Nigerian Language', 'Language and communication', 'Why is tone important in many Nigerian languages?', 'Tone always shows whether a noun is plural.', 'Tone replaces every consonant sound.', 'Tone is used only in written punctuation.', 'A change in pitch pattern can change a word’s meaning.', 'D', 'In tonal languages, pitch patterns can distinguish lexical meaning.', 'medium', '1', 'true'),
('SS1', 'arts', 'Nigerian Language', 'Oral literature', 'Which is an example of oral literature?', 'A proverb transmitted and used in spoken tradition', 'A laboratory timetable', 'A numerical data table', 'A road sign with no words', 'A', 'Proverbs are a form of oral literature passed through spoken use and tradition.', 'easy', '1', 'true'),
('SS1', 'arts', 'Nigerian Language', 'Grammar', 'In a sentence, what is the main function of a verb?', 'To name only a person or place', 'To express an action, occurrence or state', 'To link two paragraphs', 'To indicate punctuation at the end', 'B', 'Verbs express actions, events or states and form the predicate of a clause.', 'easy', '1', 'true'),
('SS1', 'arts', 'Nigerian Language', 'Translation', 'When translating an idiom into another language, what should a translator prioritise?', 'A word-for-word rendering in every case', 'The length of the source sentence only', 'The intended meaning in context', 'The first dictionary meaning regardless of context', 'C', 'Idioms often cannot be translated literally; the contextual sense should be preserved.', 'medium', '1', 'true'),
('SS1', 'arts', 'Nigerian Language', 'Writing skills', 'Which feature most improves the organisation of a formal composition?', 'Repeating one point in every paragraph', 'Changing topic without transitions', 'Leaving the main idea unstated', 'A clear introduction, ordered paragraphs and a conclusion', 'D', 'A coherent composition develops its subject in a logical structure.', 'easy', '1', 'true'),

('SS1', 'arts', 'French', 'Articles', 'Choose the correct French definite article: ___ école (the school).', 'Le', 'Les', 'La', 'Un', 'C', 'École is feminine singular, so its definite article is la; before a vowel it is written l’école.', 'easy', '1', 'true'),
('SS1', 'arts', 'French', 'Present tense', 'Complete the sentence: “Nous ___ au lycée.” (We are going to school.)', 'vais', 'vas', 'allez', 'allons', 'D', 'Aller is irregular; its first-person plural present form is allons.', 'easy', '1', 'true'),
('SS1', 'arts', 'French', 'Vocabulary', 'What does “la bibliothèque” mean in English?', 'The library', 'The bookshop', 'The classroom', 'The office', 'A', 'La bibliothèque is a library; a bookshop is usually une librairie.', 'easy', '1', 'true'),
('SS1', 'arts', 'French', 'Negation', 'Which French phrase correctly makes “Il parle” (He speaks) negative?', 'Il parle ne pas.', 'Il ne parle pas.', 'Ne il pas parle.', 'Il pas ne parle.', 'B', 'In the standard written pattern, ne and pas surround the conjugated verb.', 'medium', '1', 'true'),
('SS1', 'arts', 'French', 'Agreement', 'Choose the correct adjective: “des filles ___” (tall girls).', 'grand', 'grande', 'grandes', 'grands', 'C', 'The noun filles is feminine plural, so the adjective is grandes.', 'medium', '1', 'true'),

('SS1', 'arts', 'Arabic', 'Arabic script', 'In which direction is standard Arabic text read?', 'Right to left', 'Left to right', 'Top to bottom only', 'Alternating direction within each word', 'A', 'Standard Arabic writing proceeds from right to left.', 'easy', '1', 'true'),
('SS1', 'arts', 'Arabic', 'Grammar', 'In Arabic grammar, what is a noun (ism) generally used to name?', 'An action only', 'A person, place, thing or concept', 'A punctuation mark', 'A sentence-ending vowel only', 'B', 'An ism is a noun and can identify people, places, things and abstract concepts.', 'easy', '1', 'true'),
('SS1', 'arts', 'Arabic', 'Vocabulary', 'What does “kitāb” (كتاب) mean?', 'Pen', 'School', 'Book', 'Teacher', 'C', 'Kitāb is the Arabic word for book.', 'easy', '1', 'true'),
('SS1', 'arts', 'Arabic', 'Pronouns', 'Which Arabic pronoun means “I” in standard Modern Standard Arabic?', 'نحن', 'أنتَ', 'هم', 'أنا', 'D', 'أنا (ana) is the first-person singular pronoun “I.”', 'medium', '1', 'true'),
('SS1', 'arts', 'Arabic', 'Sentence structure', 'In a simple Arabic nominal sentence, which pair commonly forms its basic structure?', 'Subject and predicate', 'Preposition and punctuation only', 'Two verbs with no subject', 'Article and number only', 'A', 'A basic nominal sentence is commonly analysed as a subject (mubtadaʾ) and predicate (khabar).', 'medium', '1', 'true'),

('SS1', 'arts', 'Visual Arts', 'Elements of art', 'Which element describes the lightness or darkness of a colour?', 'Value', 'Texture', 'Form', 'Space', 'A', 'Value describes how light or dark a tone or colour appears.', 'easy', '1', 'true'),
('SS1', 'arts', 'Visual Arts', 'Colour theory', 'Which colour is complementary to blue in the traditional RYB colour wheel?', 'Green', 'Orange', 'Violet', 'Yellow', 'B', 'Orange lies opposite blue on the traditional red-yellow-blue colour wheel.', 'medium', '1', 'true'),
('SS1', 'arts', 'Visual Arts', 'Perspective', 'In one-point perspective, parallel lines receding directly away from the viewer appear to meet at what?', 'A colour centre', 'A ground texture', 'A vanishing point', 'A contour mark', 'C', 'Receding parallel lines converge visually at a vanishing point on the horizon.', 'medium', '1', 'true'),
('SS1', 'arts', 'Visual Arts', 'Printmaking', 'In relief printing, which part of the printing block transfers ink to paper?', 'The deepest carved grooves only', 'The back of the block', 'The table beneath the block', 'The raised surface', 'D', 'Ink is applied to the raised areas, which make contact with the paper.', 'easy', '1', 'true'),
('SS1', 'arts', 'Visual Arts', 'Art criticism', 'Which sequence is a useful starting framework for analysing an artwork?', 'Describe, analyse, interpret and evaluate', 'Advertise, price, sell and ship', 'Measure, calculate, memorise and recite', 'Sketch, erase, fold and label', 'A', 'This sequence moves from observation to analysis, interpretation and reasoned evaluation.', 'medium', '1', 'true'),

('SS1', 'arts', 'Music', 'Music notation', 'In a common-time bar, how many crotchet beats are represented by the time signature 3/4?', 'Two', 'Three', 'Four', 'Six', 'B', 'The numerator indicates three beats per bar, with the crotchet as the beat unit.', 'easy', '1', 'true'),
('SS1', 'arts', 'Music', 'Intervals', 'How many semitones are in a perfect octave in equal temperament?', '5', '7', '12', '10', 'C', 'An octave contains twelve semitone steps in equal temperament.', 'easy', '1', 'true'),
('SS1', 'arts', 'Music', 'Musical instruments', 'Which instrument belongs to the woodwind family?', 'Talking drum', 'Guitar', 'Trumpet', 'Flute', 'D', 'The flute is classified as a woodwind instrument, although modern flutes are commonly metal.', 'easy', '1', 'true'),
('SS1', 'arts', 'Music', 'Dynamics', 'What does “piano” instruct a musician to do?', 'Play softly', 'Play loudly', 'Gradually get faster', 'Repeat the previous bar', 'A', 'In musical dynamics, piano means soft or quiet.', 'easy', '1', 'true'),
('SS1', 'arts', 'Music', 'Nigerian music', 'Which instrument is a plucked lamellophone associated with several African musical traditions?', 'Trombone', 'Thumb piano (mbira)', 'Viola', 'Bassoon', 'B', 'A mbira produces sound from tuned metal or wooden tongues plucked by the thumbs.', 'medium', '1', 'true'),

('SS1', 'arts', 'Literature in English', 'Literary genres', 'A play written mainly to create serious conflict and a sad outcome is most likely a what?', 'Tragedy', 'Comedy', 'Pastoral lyric', 'Fable', 'A', 'Tragedy centres on serious conflict and commonly ends in suffering or loss.', 'easy', '1', 'true'),
('SS1', 'arts', 'Literature in English', 'Poetry', 'What is the speaker in a poem?', 'Always the poet speaking autobiographically', 'The voice that speaks in the poem', 'The person who prints the poem', 'The reader’s teacher', 'B', 'The speaker is the poetic voice and should not automatically be assumed to be the poet.', 'medium', '1', 'true'),
('SS1', 'arts', 'Literature in English', 'Figures of speech', '“Her explanation was a bridge between the two ideas” is primarily an example of what?', 'Simile', 'Onomatopoeia', 'Metaphor', 'Apostrophe', 'C', 'The sentence directly identifies the explanation with a bridge to suggest connection.', 'easy', '1', 'true'),
('SS1', 'arts', 'Literature in English', 'Prose', 'What is the setting of a prose narrative?', 'The lesson written at the end only', 'The list of characters in alphabetical order', 'The number of pages in the book', 'The time and place in which events occur', 'D', 'Setting establishes when and where the narrative takes place.', 'easy', '1', 'true'),
('SS1', 'arts', 'Literature in English', 'Drama', 'What is a soliloquy commonly used to reveal?', 'A character’s thoughts spoken aloud while alone or apparently alone', 'A stage manager’s private checklist', 'The audience’s seating arrangement', 'A narrator’s list of scene changes', 'A', 'A soliloquy lets the audience hear a character’s private thoughts.', 'medium', '1', 'true'),

('SS1', 'arts', 'Home Management', 'Management process', 'A family lists its needs, available income and planned spending before the month begins. What process is it using?', 'Budgeting', 'Food preservation', 'Interior decoration', 'Consumer credit', 'A', 'A budget is a plan for expected income and expenditure over a period.', 'easy', '1', 'true'),
('SS1', 'arts', 'Home Management', 'Consumer education', 'What should a consumer compare to find the better unit value between two differently sized products?', 'Package colour only', 'Price per equal unit of quantity', 'The number of advertisements', 'The shelf position only', 'B', 'Comparing unit prices makes differently sized packs easier to compare fairly.', 'medium', '1', 'true'),
('SS1', 'arts', 'Home Management', 'Family resources', 'Which is an example of a non-material family resource?', 'A refrigerator', 'A piece of land', 'Time', 'Cash savings', 'C', 'Time is a non-material resource that families allocate alongside money and physical goods.', 'easy', '1', 'true'),
('SS1', 'arts', 'Home Management', 'Clothing care', 'Why should a care label be checked before washing a garment?', 'It shows the garment’s resale price.', 'It guarantees that all stains will disappear.', 'It identifies the person who wore it last.', 'It gives guidance about suitable cleaning and care methods.', 'D', 'Care labels provide the maker’s recommended washing, drying and ironing instructions.', 'easy', '1', 'true'),
('SS1', 'arts', 'Home Management', 'Household safety', 'Which action reduces the risk of a kitchen fire involving cooking oil?', 'Turn off the heat if oil begins to smoke and keep water away from burning oil.', 'Leave heated oil unattended.', 'Keep the pan handle over the walkway.', 'Pour water onto an oil fire.', 'A', 'Stop heating smoking oil; water can spread burning oil, so do not pour water on an oil fire.', 'hard', '2', 'true'),

('SS1', 'arts', 'Catering Craft', 'Kitchen hygiene', 'Why should food handlers wash hands before preparing ready-to-eat food?', 'To increase the food’s cooking time', 'To make refrigeration unnecessary', 'To remove the need for clean utensils', 'To reduce transfer of microorganisms to food', 'D', 'Handwashing reduces the transfer of pathogens from hands to food and equipment.', 'easy', '1', 'true'),
('SS1', 'arts', 'Catering Craft', 'Food preparation', 'Which knife technique keeps fingertips safer while chopping vegetables?', 'Curl fingertips inward and guide the blade with the knuckles', 'Hold the food with fingertips stretched toward the blade', 'Chop while carrying the knife in the air', 'Use a blunt knife and press harder', 'A', 'A tucked “claw” grip keeps fingertips away from the cutting edge while guiding the knife.', 'medium', '1', 'true'),
('SS1', 'arts', 'Catering Craft', 'Cooking methods', 'Which method cooks food using dry heat in an enclosed heated space?', 'Poaching', 'Baking', 'Stewing', 'Boiling', 'B', 'Baking uses dry heat in an oven, unlike moist-heat methods such as boiling or poaching.', 'easy', '1', 'true'),
('SS1', 'arts', 'Catering Craft', 'Menu planning', 'When planning a meal for a customer with a stated food allergy, what should a caterer do first?', 'Remove the allergen from the menu description only.', 'Assume a small amount is safe for everyone.', 'Check ingredients and prevent cross-contact with the allergen.', 'Use the same unwashed utensils for every dish.', 'C', 'Ingredient checks and preventing cross-contact are essential steps for managing allergy risk.', 'hard', '2', 'true'),
('SS1', 'arts', 'Catering Craft', 'Food storage', 'Which practice is safest for refrigerated leftovers?', 'Leave them uncovered at room temperature overnight.', 'Mix them with raw meat in one container.', 'Store them indefinitely because refrigeration stops all spoilage.', 'Cool and store them promptly in covered, labelled containers.', 'D', 'Prompt cooling and covered, labelled storage help limit contamination and support safe use.', 'medium', '1', 'true')
on conflict do nothing;
