-- SS1 common/core starter batch: five newly authored questions per subject.
-- Common subjects use a null category; all rows are active and reruns are
-- duplicate-safe through the question-bank level/subject/prompt unique index.
insert into public.question_bank (
  level, category, subject, topic, question,
  option_a, option_b, option_c, option_d, correct_answer,
  explanation, difficulty, marks, is_active
) values
('SS1', null, 'English Language', 'Clauses', 'In the sentence “Although the road was flooded, the bus continued,” which words form the subordinate clause?', 'Although the road was flooded', 'the bus continued', 'the road was flooded, the bus', 'Although the bus continued', 'A', 'The clause begins with the subordinating conjunction “although” and cannot stand alone as a complete sentence.', 'medium', '1', 'true'),
('SS1', null, 'English Language', 'Concord', 'Choose the correct verb: “Neither the laboratory equipment nor the chemicals ___ ready.”', 'is', 'are', 'was', 'has been', 'B', 'With neither…nor, the verb agrees with the nearer subject; “chemicals” is plural.', 'medium', '1', 'true'),
('SS1', null, 'English Language', 'Vocabulary in context', 'In “The committee reached a unanimous decision,” what does “unanimous” mean?', 'Made after a long delay', 'Based on secret evidence', 'Supported by all members', 'Changed several times', 'C', 'A unanimous decision is one that all members support.', 'easy', '1', 'true'),
('SS1', null, 'English Language', 'Literary devices', '“The old generator coughed and spluttered before starting” uses which device?', 'Oxymoron', 'Onomatopoeia only', 'Euphemism', 'Personification', 'D', 'The generator is given human actions, so the sentence uses personification.', 'easy', '1', 'true'),
('SS1', null, 'English Language', 'Punctuation', 'Which sentence punctuates the direct address correctly?', 'Students, bring your notebooks to class.', 'Students bring your notebooks to class.', 'Students bring, your notebooks to class.', 'Students bring your, notebooks to class.', 'A', 'A comma separates the noun used to address the students from the command.', 'easy', '1', 'true'),

('SS1', null, 'General Mathematics', 'Number bases', 'What is 101101₂ expressed in base ten?', '41', '43', '45', '47', 'C', '101101₂ = 32 + 8 + 4 + 1 = 45.', 'medium', '1', 'true'),
('SS1', null, 'General Mathematics', 'Sets', 'In a class of 32 students, 19 study Biology, 15 study Chemistry and 7 study both. How many study neither subject?', '3', '7', '9', '5', 'D', 'At least one = 19 + 15 − 7 = 27; neither = 32 − 27 = 5.', 'hard', '2', 'true'),
('SS1', null, 'General Mathematics', 'Linear inequalities', 'Solve 3x − 4 < 11.', 'x < 5', 'x > 5', 'x < 7/3', 'x > 7/3', 'A', 'Adding 4 gives 3x < 15; dividing by 3 gives x < 5.', 'medium', '1', 'true'),
('SS1', null, 'General Mathematics', 'Coordinate geometry', 'Find the gradient of the line through (−2, 1) and (4, 13).', '1', '2', '3', '6', 'B', 'Gradient = (13 − 1) ÷ (4 − (−2)) = 12 ÷ 6 = 2.', 'medium', '1', 'true'),
('SS1', null, 'General Mathematics', 'Trigonometry', 'A right-angled triangle has an opposite side of 5 cm and an adjacent side of 12 cm to angle θ. What is tan θ?', '12/5', '5/13', '5/12', '12/13', 'C', 'Tangent is opposite divided by adjacent, so tan θ = 5/12.', 'easy', '1', 'true'),

('SS1', null, 'Digital Technologies', 'Data representation', 'How many different values can an unsigned 8-bit binary number represent?', '8', '128', '256', '255', 'C', 'Eight bits give 2⁸ combinations, which is 256 values from 0 to 255.', 'medium', '1', 'true'),
('SS1', null, 'Digital Technologies', 'Spreadsheets', 'Cells B2:B6 contain five scores. Which formula calculates their arithmetic mean?', '=MEAN(B2:B6)', '=MID(B2:B6)', '=COUNT(B2:B6)', '=AVERAGE(B2:B6)', 'D', 'AVERAGE returns the arithmetic mean of the numeric values in the range.', 'easy', '1', 'true'),
('SS1', null, 'Digital Technologies', 'Programming', 'A program must repeat a task exactly eight times. Which control structure is most suitable?', 'A fixed-count loop', 'A selection statement with no condition', 'A comment line', 'A variable declaration only', 'A', 'A count-controlled loop repeats a block a specified number of times.', 'easy', '1', 'true'),
('SS1', null, 'Digital Technologies', 'Relational databases', 'An order must be linked to the customer who placed it. Which design supports this relationship?', 'Store the customer’s address as the order number.', 'Store a customer_id in the order record that references the customer table.', 'Put each order in a separate database.', 'Use the customer’s name as the only link and repeat it in every field.', 'B', 'A foreign key such as customer_id can reference the customer table and connect each order to its customer.', 'medium', '1', 'true'),
('SS1', null, 'Digital Technologies', 'Cybersecurity', 'A student receives an email asking them to sign in through an unfamiliar link to keep an account active. What is the safest response?', 'Use the link quickly before the account closes.', 'Reply with the account password.', 'Open the service using its known address and report the suspicious email.', 'Forward the message to classmates to verify it.', 'C', 'This may be phishing; use a trusted route to the service and report the message without sharing credentials.', 'hard', '2', 'true'),

('SS1', null, 'Citizenship and Heritage Studies', 'Constitutional supremacy', 'A government order conflicts with a clear provision of the constitution. In a constitutional democracy, what should guide the resolution?', 'The personal preference of the official who issued the order', 'The oldest newspaper report', 'A private company’s internal rules', 'The constitution and lawful judicial interpretation', 'D', 'Constitutional supremacy means public authorities must act within the constitution, subject to lawful interpretation.', 'medium', '1', 'true'),
('SS1', null, 'Citizenship and Heritage Studies', 'Rights and responsibilities', 'A student’s right to express an opinion is best exercised by doing what?', 'Expressing the view respectfully and lawfully', 'Making threats against people who disagree', 'Sharing private information about others', 'Preventing others from speaking', 'A', 'Rights should be exercised in ways that respect the rights and safety of others.', 'easy', '1', 'true'),
('SS1', null, 'Citizenship and Heritage Studies', 'Democratic participation', 'Why is an independent judiciary important in a democracy?', 'It gives judges power to write every government policy.', 'It allows courts to decide legal disputes without improper control.', 'It removes the need for laws.', 'It allows officials to ignore court decisions.', 'B', 'Judicial independence supports impartial interpretation of law and protection of rights.', 'medium', '1', 'true'),
('SS1', null, 'Citizenship and Heritage Studies', 'Nigerian identity', 'Which action is an example of preserving Nigeria’s intangible cultural heritage?', 'Replacing local languages with one foreign language', 'Removing traditional music from public archives', 'Recording and teaching a community’s oral tradition with its custodians’ consent', 'Selling an artefact without recording its origin', 'C', 'Oral knowledge, language and performance are intangible heritage that can be documented respectfully.', 'medium', '1', 'true'),
('SS1', null, 'Citizenship and Heritage Studies', 'Public accountability', 'A citizen suspects that public funds were misused. Which action best supports accountability?', 'Spread an unverified accusation online.', 'Damage the public office building.', 'Publish another person’s private records.', 'Use an appropriate reporting or oversight channel and provide evidence.', 'D', 'Reporting through lawful oversight channels with verifiable evidence supports accountability and due process.', 'hard', '2', 'true')
on conflict do nothing;
