"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { ArrowUpRight, Bell, BookOpen, CalendarDays, CheckCircle2, ClipboardList, House, LogOut, Menu, UserRound, Wallet, X } from "lucide-react";
import type { StudentSession } from "../lib/student-store";

const groups = [
  { title: "Overview", items: [{ label: "Dashboard", href: "/dashboard", icon: House }] },
  { title: "Academics", items: [{ label: "My Subjects", href: "/courses", icon: BookOpen }, { label: "CBT / Exams", href: "/cbt", icon: CheckCircle2 }, { label: "Results", href: "/results", icon: ClipboardList }, { label: "Timetable", href: "/timetable", icon: CalendarDays }] },
  { title: "School", items: [{ label: "Fees & Payments", href: "/fees", icon: Wallet }, { label: "Announcements", href: "/announcements", icon: Bell }, { label: "My Profile", href: "/profile", icon: UserRound }] },
];

export function StudentPortalShell({ title, student, period, onLogout, children }: { title: string; student?: StudentSession | null; period?: string; onLogout?: () => void; children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const initials = student?.fullName.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase() ?? "U";
  return <div className="min-h-screen bg-[#f5f6fa] text-slate-900 dark:bg-slate-950 dark:text-slate-100 md:flex">
    <div className={`${open ? "fixed inset-0 z-40 bg-slate-950/55" : "hidden"} md:sticky md:top-0 md:block md:h-screen md:w-[264px] md:shrink-0`} onClick={() => setOpen(false)}>
      <aside onClick={(event) => event.stopPropagation()} className={`absolute inset-y-0 left-0 flex w-[278px] max-w-[86vw] flex-col bg-[#111827] text-slate-300 shadow-2xl transition-transform md:relative md:h-screen md:w-full md:max-w-none md:shadow-none ${open ? "translate-x-0" : "-translate-x-full md:translate-x-0"}`}>
        <div className="flex h-[76px] shrink-0 items-center justify-between border-b border-white/10 px-5"><Link href="/dashboard" onClick={() => setOpen(false)} className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500 text-lg font-bold text-white">U</span><span><span className="block text-sm font-bold tracking-[.1em] text-white">UNIALEGE</span><span className="mt-0.5 block text-[10px] tracking-wide text-slate-400">STUDENT PORTAL</span></span></Link><button type="button" onClick={() => setOpen(false)} aria-label="Close navigation" className="rounded-md p-2 text-slate-400 hover:bg-white/10 md:hidden"><X className="h-5 w-5" /></button></div>
        <nav aria-label="Student navigation" className="flex-1 overflow-y-auto px-3 py-5">{groups.map((group) => <div key={group.title} className="mb-6"><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-500">{group.title}</p><div className="space-y-1">{group.items.map(({ label, href, icon: Icon }) => { const active = label === title || (title === "School Fees" && href === "/fees") || (title === "Class Timetable" && href === "/timetable") || (title === "Profile & Account Settings" && href === "/profile") || (title === "CBT / Exams" && href === "/cbt"); return <Link key={href} href={href} onClick={() => setOpen(false)} aria-current={active ? "page" : undefined} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium ${active ? "bg-blue-600 text-white" : "text-slate-400 hover:bg-white/[.06] hover:text-white"}`}><Icon className="h-[18px] w-[18px]" strokeWidth={1.8} /><span>{label}</span>{active && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-white" />}</Link>; })}</div></div>)}</nav>
        {student && <div className="shrink-0 border-t border-white/10 p-3"><Link href="/profile" className="flex min-w-0 items-center gap-3 rounded-lg p-2.5 hover:bg-white/[.06]"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-blue-500/20 text-xs font-bold text-blue-200">{initials}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-white">{student.fullName}</span><span className="mt-1 block truncate text-[10px] text-slate-400">{student.className} · {student.admissionNumber}</span></span><ArrowUpRight className="h-4 w-4 text-slate-500" /></Link>{onLogout && <Link href="/login" onClick={onLogout} className="mt-1 flex items-center gap-3 rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-red-500/10 hover:text-red-300"><LogOut className="h-4 w-4" />Sign out</Link>}</div>}
        {!student && <div className="border-t border-white/10 p-4"><Link href="/dashboard" className="text-xs text-slate-400 hover:text-white">Return to dashboard <ArrowUpRight className="inline h-3 w-3" /></Link></div>}
      </aside>
    </div>
    <div className="min-w-0 flex-1">
      <header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-slate-200/80 bg-white/95 px-4 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-900/95 sm:px-7 lg:px-9"><div className="flex min-w-0 items-center gap-3"><button type="button" onClick={() => setOpen(true)} aria-label="Open navigation" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-slate-200 text-slate-600 dark:border-slate-700 dark:text-slate-300 md:hidden"><Menu className="h-5 w-5" /></button><div className="min-w-0"><p className="truncate text-[11px] text-slate-400">Student portal <span className="px-1 text-slate-300">/</span>{title}</p><h1 className="mt-0.5 truncate text-sm font-semibold tracking-tight text-slate-900 dark:text-white">{title}</h1></div></div><div className="flex shrink-0 items-center gap-2 sm:gap-4">{period && <span className="hidden text-right text-[11px] text-slate-500 sm:block">{period}</span>}<Link href="/announcements" aria-label="Announcements" className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-500 dark:border-slate-700 dark:text-slate-300"><Bell className="h-[18px] w-[18px]" /></Link>{student && <Link href="/profile" aria-label={`${student.fullName} profile`} className="flex h-9 w-9 items-center justify-center rounded-full bg-indigo-100 text-xs font-bold text-indigo-700 dark:bg-indigo-400/15 dark:text-indigo-200">{initials}</Link>}</div></header>
      <main className="mx-auto w-full max-w-[1500px] space-y-6 px-4 py-6 sm:px-7 sm:py-8 lg:px-10">{children}<footer className="pb-3 text-center text-[10px] text-slate-400">© 2026 UniAllege · Student portal</footer></main>
    </div>
  </div>;
}
